### ISSUE TITLE
How do I turn off calls Get / Set Data Module functions?

### ISSUE THREAD

**Issue by skittonik** [defold/extension-crazygames#3]
I only use localStorage in my game, but Crazy Games moderation rejects the game the way it uses get/set from Data Module.
How do I turn off calls Get / Set?

![image](https://github.com/user-attachments/assets/463519fb-7392-411c-b43b-0694a4a6a101)

Moderator's response:
"We noticed the game still calls Data Module functions (get and set). Please remove it since only one of them (Local Storage or Data Module) will be backed up by our system. However, we suggest changing to the Data Module since it is more reliable than LocalStorage (suggestion)."

**Comment by britzl** [comment]
This version of the CrazyGames SDK integration in Defold does not yet support the Data module:

https://github.com/defold/extension-crazygames/issues/2

We expect to add support for Data module later this week.

**Comment by skittonik** [comment]
I'm sorry, it was another module that sent these calls
